image: python:3.9

cache:
  paths:
    - .cache/pip

before_script:
  - pip install mkdocs-material
  - pip install mkdocs-macros-plugin

pages:
  script:
    - mkdocs gh-deploy
  artifacts:
    paths:
      - public
  only:
    - main
